#!/usr/bin/env python

import sys

import aile

usage = """
{0} url

Will generate a directory 'slybot-project' with the necessary files.
Execute after this:

    slybot crawl aile

Edit the project files to add other urls to be crawled and rename fields, etc...
"""

if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(usage)
    url = sys.argv[1]

    aile.generate_slybot_project(url, verbose=True)
